import Head from 'next/head'
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <meta name='viewport' content='width=device-width' />
      </Head>
      <html lang="en">
        <body className={inter.className}>
            {children}
        </body>
      </html>
    </>

  );
}
